version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: insecure-password
      MYSQL_DATABASE: CategorizerDb
      MYSQL_ROOT_HOST: "172.17.0.1" # Default Docker Gateway.. allow only connections from this machine
    command: --lower_case_table_names=1
    volumes: 
      - ./build_scripts/database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql